#!/usr/bin/env bash
python optimize_bce.py #

# Focal Loss Ablation
python main.py --experiment a_focal --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights uniform --thresholding class_specific --loss focal --device cuda:0 --model lstm --gamma 0.0 &
python main.py --experiment a_focal --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights uniform --thresholding class_specific --loss focal --device cuda:0 --model lstm --gamma 0.5 &
python main.py --experiment a_focal --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights uniform --thresholding class_specific --loss focal --device cuda:1 --model lstm --gamma 1.0 &
python main.py --experiment a_focal --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights uniform --thresholding class_specific --loss focal --device cuda:1 --model lstm --gamma 2.0 &
python main.py --experiment a_focal --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights uniform --thresholding class_specific --loss focal --device cuda:1 --model lstm --gamma 4.0 &
wait

# Dynamic Loss Size Ablation
python main.py --experiment a_dynamic_weigthing_gamma2 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss bce --model lstm --gamma 2.0 --weights uniform --device cuda:0 &
python main.py --experiment a_dynamic_weigthing_gamma2 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 2.0 --weights dynamic_loss_size --weight_smoothing 0.1 --device cuda:1 &
python main.py --experiment a_dynamic_weigthing_gamma2 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 2.0 --weights dynamic_loss_size --weight_smoothing 0.2 --device cuda:2 &
python main.py --experiment a_dynamic_weigthing_gamma2 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 2.0 --weights dynamic_loss_size --weight_smoothing 0.3 --device cuda:3 &
python main.py --experiment a_dynamic_weigthing_gamma2 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 2.0 --weights dynamic_loss_size --weight_smoothing 0.4 --device cuda:4 &
python main.py --experiment a_dynamic_weigthing_gamma2 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 2.0 --weights dynamic_loss_size --weight_smoothing 0.5 --device cuda:5 &
python main.py --experiment a_dynamic_weigthing_gamma2 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 2.0 --weights dynamic_loss_size --weight_smoothing 0.6 --device cuda:0 &
python main.py --experiment a_dynamic_weigthing_gamma2 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 2.0 --weights dynamic_loss_size --weight_smoothing 0.7 --device cuda:1 &
python main.py --experiment a_dynamic_weigthing_gamma2 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 2.0 --weights dynamic_loss_size --weight_smoothing 0.8 --device cuda:2 &
python main.py --experiment a_dynamic_weigthing_gamma2 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 2.0 --weights dynamic_loss_size --weight_smoothing 0.9 --device cuda:3 &
python main.py --experiment a_dynamic_weigthing_gamma2 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 2.0 --weights dynamic_loss_size --weight_smoothing 1.0 --device cuda:4 &

python main.py --experiment a_dynamic_weigthing_gamma0 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 0 --weights dynamic_loss_size --weight_smoothing 0.0 --device cuda:0 &
python main.py --experiment a_dynamic_weigthing_gamma0 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 0 --weights dynamic_loss_size --weight_smoothing 0.1 --device cuda:1 &
python main.py --experiment a_dynamic_weigthing_gamma0 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 0 --weights dynamic_loss_size --weight_smoothing 0.2 --device cuda:2 &
python main.py --experiment a_dynamic_weigthing_gamma0 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 0 --weights dynamic_loss_size --weight_smoothing 0.3 --device cuda:3 &
python main.py --experiment a_dynamic_weigthing_gamma0 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 0 --weights dynamic_loss_size --weight_smoothing 0.4 --device cuda:4 &
python main.py --experiment a_dynamic_weigthing_gamma0 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 0 --weights dynamic_loss_size --weight_smoothing 0.5 --device cuda:5 &
python main.py --experiment a_dynamic_weigthing_gamma0 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 0 --weights dynamic_loss_size --weight_smoothing 0.6 --device cuda:0 &
python main.py --experiment a_dynamic_weigthing_gamma0 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 0 --weights dynamic_loss_size --weight_smoothing 0.7 --device cuda:1 &
python main.py --experiment a_dynamic_weigthing_gamma0 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 0 --weights dynamic_loss_size --weight_smoothing 0.8 --device cuda:2 &
python main.py --experiment a_dynamic_weigthing_gamma0 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 0 --weights dynamic_loss_size --weight_smoothing 0.9 --device cuda:3 &
python main.py --experiment a_dynamic_weigthing_gamma0 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 0 --weights dynamic_loss_size --weight_smoothing 1.0 --device cuda:4 &

python main.py --experiment a_center_loss --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal_center --model lstm --gamma 2.0 --weights dynamic_loss_size --weight_smoothing 1.0 --device cuda:0 --lambda 0 --lr_center 0.5 --lambda 0.003 &
python main.py --experiment a_center_loss --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal_center --model lstm --gamma 2.0 --weights dynamic_loss_size --weight_smoothing 1.0 --device cuda:1 --lambda 0 --lr_center 0.5 --lambda 0.001 &
python main.py --experiment a_center_loss --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal_center --model lstm --gamma 2.0 --weights dynamic_loss_size --weight_smoothing 1.0 --device cuda:2 --lambda 0 --lr_center 0.5 --lambda 0.01 &
python main.py --experiment a_center_loss --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal_center --model lstm --gamma 2.0 --weights dynamic_loss_size --weight_smoothing 1.0 --device cuda:3 --lambda 0 --lr_center 0.5 --lambda 0.1 &
python main.py --experiment a_center_loss --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal_center --model lstm --gamma 2.0 --weights dynamic_loss_size --weight_smoothing 1.0 --device cuda:4 --lambda 0 --lr_center 0.5 --lambda 0.0001 &


python main.py --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding minimized_expectation --loss focal --model lstm --gamma 0 --weights dynamic_loss_size --weight_smoothing 1.0 --device cuda:5
python main.py --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding minimized_expectation --loss focal --model lstm --gamma 2.0 --weights dynamic_loss_size --weight_smoothing 1.0 --device cuda:5

python main.py --experiment ablation_weighting --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights inverse --thresholding class_specific --loss focal --device cuda:0 --model lstm --gamma 2.0 &
python main.py --experiment ablation_weighting --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights cost_sensitive --thresholding class_specific --loss focal --device cuda:0 --model lstm --gamma 2.0 &

python main.py --experiment ablation_weighting --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights inverse --thresholding class_specific --loss focal --device cuda:0 --model lstm --gamma 0 &
python main.py --experiment ablation_weighting --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights cost_sensitive --thresholding class_specific --loss focal --device cuda:0 --model lstm --gamma 0 &

python main.py --experiment a_dynamic_weigthing_gamma0 --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --thresholding class_specific --loss focal --model lstm --gamma 0 --weights dynamic_loss_size --weight_smoothing 1.0 --device cuda:4 --lr_center 0.001 --lambda 0.001 &

####


python main.py --experiment ablation_loss_test --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights uniform --thresholding class_specific --loss focal --gamma 0 --device cuda:4 &
python main.py --experiment ablation_loss_test --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights uniform --thresholding class_specific --loss focal --gamma 0.5 --device cuda:0 &
python main.py --experiment ablation_loss_test --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights uniform --thresholding class_specific --loss focal --gamma 1.0 --device cuda:1 &
python main.py --experiment ablation_loss_test --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights uniform --thresholding class_specific --loss focal --gamma 2.0 --device cuda:2 &
python main.py --experiment ablation_loss_test --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights uniform --thresholding class_specific --loss focal --gamma 4.0 --device cuda:3 &
wait

python main.py --experiment ablation_loss_ws --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights dynamic_loss_size --thresholding class_specific --loss focal --gamma 2.0 --device cuda:2 --weight_smoothing 0.001 &
python main.py --experiment ablation_loss_ws --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights dynamic_loss_size --thresholding class_specific --loss focal --gamma 2.0 --device cuda:2 --weight_smoothing 0.005 &
python main.py --experiment ablation_loss_ws --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights dynamic_loss_size --thresholding class_specific --loss focal --gamma 2.0 --device cuda:2 --weight_smoothing 0.01 &
python main.py --experiment ablation_loss_ws --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights dynamic_loss_size --thresholding class_specific --loss focal --gamma 2.0 --device cuda:2 --weight_smoothing 0.01 &
python main.py --experiment ablation_loss_ws --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights dynamic_loss_size --thresholding class_specific --loss focal --gamma 2.0 --device cuda:2 --weight_smoothing 0.25 &
python main.py --experiment ablation_loss_ws --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights dynamic_loss_size --thresholding class_specific --loss focal --gamma 2.0 --device cuda:2 --weight_smoothing 0.5 &
python main.py --experiment ablation_loss_ws --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights dynamic_loss_size --thresholding class_specific --loss focal --gamma 2.0 --device cuda:2 --weight_smoothing 0.75 &
python main.py --experiment ablation_loss_ws --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights dynamic_loss_size --thresholding class_specific --loss focal --gamma 2.0 --device cuda:2 --weight_smoothing 0.9 &
python main.py --experiment ablation_loss_ws --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights dynamic_loss_size --thresholding class_specific --loss focal --gamma 2.0 --device cuda:2 --weight_smoothing 1.0 &
wait

python main.py --experiment ablation_entropy_der --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights equal_entropy --thresholding class_specific --loss focal --gamma 2.0 --device cuda:0 --weight_smoothing 0.001 &
python main.py --experiment ablation_entropy_der --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights equal_entropy --thresholding class_specific --loss focal --gamma 2.0 --device cuda:0 --weight_smoothing 0.005 &
python main.py --experiment ablation_entropy_der --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights equal_entropy --thresholding class_specific --loss focal --gamma 2.0 --device cuda:1 --weight_smoothing 0.01 &
python main.py --experiment ablation_entropy_der --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights equal_entropy --thresholding class_specific --loss focal --gamma 2.0 --device cuda:1 --weight_smoothing 0.01 &
python main.py --experiment ablation_entropy_der --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights equal_entropy --thresholding class_specific --loss focal --gamma 2.0 --device cuda:2 --weight_smoothing 0.25 &
python main.py --experiment ablation_entropy_der --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights equal_entropy --thresholding class_specific --loss focal --gamma 2.0 --device cuda:2 --weight_smoothing 0.5 &
python main.py --experiment ablation_entropy_der --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights equal_entropy --thresholding class_specific --loss focal --gamma 2.0 --device cuda:3 --weight_smoothing 0.75 &
python main.py --experiment ablation_entropy_der --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights equal_entropy --thresholding class_specific --loss focal --gamma 2.0 --device cuda:3 --weight_smoothing 0.9 &
python main.py --experiment ablation_entropy_der --data SemEval_Arabic_English_Spanish --dropout 0.25 --lr 0.001 --weight_decay 1e-7 --hidden_size 128 --weights equal_entropy --thresholding class_specific --loss focal --gamma 2.0 --device cuda:4 --weight_smoothing 1.0 &
wait